name: Build

on:
  push:
    branches: [ Hojat_Main_Branch ]
  pull_request:
    branches: [ Hojat_Main_Branch ]

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: [ ubuntu-latest ]
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate a Cache Key
        run: ./checksum.sh checksum.txt

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Cache Gradle Folders
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            cache-gradle-${{ runner.os }}-
            cache-gradle-


      - name: Run Static Analysis Tools
        run: ./gradlew lint ktlintCheck --continue

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload APK
        uses: actions/upload-artifact@v2.1.4
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk

  unit-test:
    name: Unit Tests
    runs-on: [ ubuntu-latest ]
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate a Cache Key
        run: ./checksum.sh checksum.txt

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Cache Gradle Folders
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            cache-gradle-${{ runner.os }}-
            cache-gradle-

      - name: Run Unit Tests
        run: ./gradlew test

  instrumentation-test:
    name: Instrumentation Tests
    runs-on: [ macos-latest ]
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate a Cache Key
        run: ./checksum.sh checksum.txt

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Cache Gradle Folders
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            cache-gradle-${{ runner.os }}-
            cache-gradle-

      - name: Run Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis # https://github.com/ReactiveCircus/android-emulator-runner/issues/106
          script: ./gradlew connectedAndroidTest

  assemble:
    name: App Assembling
    runs-on: [ ubuntu-latest ]
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate a Cache Key
        run: ./checksum.sh checksum.txt

      - name: Copy CI Gradle Properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Cache Gradle Folders
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle-${{ runner.os }}-${{ hashFiles('checksum.txt') }}
          restore-keys: |
            cache-gradle-${{ runner.os }}-
            cache-gradle-

      - name: Build Debug APK
        run: ./gradlew assembleDebug
